//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chairs
    {
        public Chairs()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id { get; set; }
        public int Id_Hall { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
    
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
