//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public int Id_Session { get; set; }
        public int Id_Chair { get; set; }
        public decimal Price { get; set; }
    
        public virtual Chairs Chairs { get; set; }
        public virtual Sessions Sessions { get; set; }
    }
}
